# Generated by Django 5.2.7 on 2026-02-09 18:27

import django.utils.timezone
import shortuuid.django_fields
import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        default="audience.jpg",
                        null=True,
                        upload_to="audience",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "audience",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "sub_total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("cart_id", models.CharField(blank=True, max_length=1000, null=True)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CartOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("cancelled", "Cancelled"),
                            ("initiated", "Initiated"),
                            ("failed", "failed"),
                            ("refunding", "refunding"),
                            ("refunded", "refunded"),
                            ("unpaid", "unpaid"),
                            ("expired", "expired"),
                        ],
                        default="initiated",
                        max_length=100,
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Fulfilled", "Fulfilled"),
                            ("Partially Fulfilled", "Partially Fulfilled"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=100,
                    ),
                ),
                (
                    "initial_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="The original total before discounts",
                        max_digits=12,
                    ),
                ),
                (
                    "saved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Amount saved by customer",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=1000)),
                ("email", models.CharField(max_length=1000)),
                ("mobile", models.CharField(max_length=1000)),
                ("address", models.CharField(blank=True, max_length=1000, null=True)),
                ("city", models.CharField(blank=True, max_length=1000, null=True)),
                ("state", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "oid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvxyz",
                        length=10,
                        max_length=25,
                        prefix="",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "Cart Order",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CartOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField(default=0)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Total of Product price * Product Qty",
                        max_digits=12,
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Estimated Shipping Fee = shipping_fee * total",
                        max_digits=12,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Grand Total of all amount listed above",
                        max_digits=12,
                    ),
                ),
                (
                    "expected_delivery_date_from",
                    models.DateField(blank=True, null=True),
                ),
                ("expected_delivery_date_to", models.DateField(blank=True, null=True)),
                (
                    "initial_total",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Grand Total of all amount listed above before discount",
                        max_digits=12,
                    ),
                ),
                (
                    "saved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        help_text="Amount saved by customer",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("order_placed", models.BooleanField(default=False)),
                ("processing_order", models.BooleanField(default=False)),
                ("quality_check", models.BooleanField(default=False)),
                ("product_shipped", models.BooleanField(default=False)),
                ("product_arrived", models.BooleanField(default=False)),
                ("product_delivered", models.BooleanField(default=False)),
                (
                    "oid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvxyz",
                        length=10,
                        max_length=25,
                        prefix="",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "Cart Order Item",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ClothingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        default="clothing_type.jpg",
                        null=True,
                        upload_to="clothing_type",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "clothing_type",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color_code", models.CharField(max_length=100)),
                (
                    "color_text",
                    models.CharField(
                        blank=True, default="#ffffff", max_length=100, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        default="/gallery.jpg",
                        upload_to=userauths.models.user_directory_path,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("gid", models.CharField(editable=False, max_length=20, unique=True)),
            ],
            options={
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        default="product.jpg",
                        null=True,
                        upload_to="product",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "old_price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("stock_qty", models.PositiveIntegerField(default=1)),
                ("in_stock", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("disabled", "Disabled"),
                            ("in_review", "In Review"),
                            ("published", "Published"),
                        ],
                        default="published",
                        max_length=100,
                    ),
                ),
                (
                    "orders",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "saved",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("special_offer", models.BooleanField(default=False)),
                ("featured", models.BooleanField(default=False)),
                ("views", models.PositiveIntegerField(default=0)),
                ("rating", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "pid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh",
                        length=10,
                        max_length=12,
                        prefix="",
                        unique=True,
                    ),
                ),
                (
                    "sku",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=5,
                        max_length=50,
                        prefix="SKU",
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, null=True, unique=True
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "Products",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ProductFaq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("question", models.CharField(max_length=1000)),
                ("answer", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Product Faqs",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply", models.TextField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 star"),
                            (2, "2 star"),
                            (3, "3 star"),
                            (4, "4 star"),
                            (5, "5 star"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Product Reviews",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("content", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Wishlist",
            },
        ),
    ]
